[features]
seeds = false
skip-lint = false
[programs.localnet]
drift_vaults = "VAULtLeTwwUxpwAw98E6XmgaDeQucKgV5UaiAuQ655D"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"
program = "./deps/drift.so"

[scripts]
test = "yarn anchor-tests"
