name: Deploy on sdk update
on:
  repository_dispatch:
    types: [sdk-update]

jobs:
  update-sdk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: yarn install

    - name: Add specific version of sdk
      run: yarn add --dev @drift-labs/sdk@${{ github.event.client_payload.version }}

    - name: Add specific version of sdk to peer dependencies
      run: yarn add --peer @drift-labs/sdk@${{ github.event.client_payload.version }}
      working-directory: ts/sdk

    - name: Build after new dependency
      run: yarn run build
      working-directory: ts/sdk

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
        git add -A 
        git commit --allow-empty -m "Bumping sdk dependency to ${{ github.event.client_payload.version }}" --no-verify
        git push